In [1]:
import pandas as pd
import os
import glob
import numpy as np
from functools import reduce

In [2]:
os.chdir('/Users/rubencito/CAS_datascience/ADS_CAS_Bern_2020/Projects/M3/curated_datasets')
path = os.getcwd()
path

'/Users/rubencito/CAS_datascience/ADS_CAS_Bern_2020/Projects/M3/curated_datasets'

In [3]:
# define a function to merge on all datasets located at the folder "curated_datasets"
def get_merged_csv(flist, **kwargs):
    file_path = os.path.join("WB_Geo_and_Eco_groups.csv")
    geo = pd.read_csv(file_path)
    for file in flist:
        my_indi = pd.read_csv(file, **kwargs)
        geo = geo.merge(my_indi, how= "left")#, on = ["country_code", "year"])
    return(geo)

In [4]:
glob.glob('*_df.csv')

['UNDP_LifeExpecIndx_df.csv',
 'Civil_lib_indx_df.csv',
 'WB_Env_2_df.csv',
 'UNDP_FemParlmt_df.csv',
 'UNDP_GDI_df.csv',
 'UNDP_HealthExpend_df.csv',
 'UNDP_TotPopulMill_df.csv',
 'TI_CPI_df.csv',
 'UNDP_HDI_df.csv',
 'Revolution_final_df.csv',
 'Type_of_cchange_df.csv',
 'UNDP_GII_df.csv',
 'WB_Env_1_df.csv',
 'FRHA_PRIndx_score_df.csv',
 'WB_GEI_indx_df.csv',
 'UNDP_EducaIndx_df.csv',
 'WB_GNI_PPP_df.csv']

In [5]:
pd.concat((pd.read_csv(file, header = None, nrows = 1) for file in glob.glob('*_df.csv')))

,0,1,2,3
0,country_name,country_code,year,Life expectancy index
0,country_name,country_code,year,Civil liberties index
0,country_name,country_code,year,CPIA policy and institutions for environmental...
0,country_name,country_code,year,Share of seats in parliament (% held by women)
0,country_name,country_code,year,Gender Development Index (GDI)
0,country_name,country_code,year,Current health expenditure (% of GDP)
0,country_name,country_code,year,Total population (millions)
0,country_name,country_code,year,CPI_score
0,country_name,country_code,year,Human Development Index (HDI)
0,country_name,country_code,year,Revolution
0,country_name,country_code,year,type_of_change
0,country_name,country_code,year,Gender Inequality Index (GII)
0,country_name,country_code,year,CPIA business regulatory environment rating (1...
0,country_name,country_code,year,PRIndx_score
0,country_name,country_code,year,"CPIA transparency, accountability, and corrupt..."
0,country_name,country_code,year,Education index
0,country_name,country_code,year,"GNI, PPP (current international $)"

In [6]:
merged_df = get_merged_csv(glob.glob('*_df.csv'), dtype = {"year" : 'Int64'})
merged_df

,country_name,country_code,Geografical_Region,Economy_Group,year,Life expectancy index,Civil liberties index,CPIA policy and institutions for environmental sustainability rating (1=low to 6=high),Share of seats in parliament (% held by women),Gender Development Index (GDI),...,CPI_score,Human Development Index (HDI),Revolution,type_of_change,Gender Inequality Index (GII),CPIA business regulatory environment rating (1=low to 6=high),PRIndx_score,"CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)",Education index,"GNI, PPP (current international $)"
0,Afghanistan,AFG,0,0,2010,0.631,0.548055,2.5,27.635,0.595,...,NaN,0.472,0.0,0.0,0.751,2.5,NaN,2.0,0.372,5.001196e+10
1,Afghanistan,AFG,0,0,2011,0.639,0.543847,2.5,27.635,0.609,...,NaN,0.477,0.0,0.0,0.743,2.5,NaN,2.0,0.374,5.112837e+10
2,Afghanistan,AFG,0,0,2012,0.647,0.548934,2.5,27.635,0.618,...,8.0,0.489,0.0,0.0,0.734,2.5,NaN,2.0,0.390,5.976096e+10
3,Afghanistan,AFG,0,0,2013,0.654,0.551491,2.5,27.635,0.627,...,8.0,0.496,0.0,0.0,0.724,2.5,27.0,2.0,0.398,6.526676e+10
4,Afghanistan,AFG,0,0,2014,0.661,0.550697,2.5,27.635,0.634,...,12.0,0.500,0.0,0.0,0.714,2.5,26.0,2.0,0.403,6.905035e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716,Zimbabwe,ZWE,3,2,2015,0.608,0.457305,3.5,35.143,0.927,...,21.0,0.553,0.0,0.0,0.546,2.0,28.0,2.0,0.560,3.334068e+10
1717,Zimbabwe,ZWE,3,2,2016,0.620,0.407481,4.0,35.143,0.927,...,22.0,0.558,0.0,0.0,0.541,2.0,32.0,2.0,0.565,3.597303e+10
1718,Zimbabwe,ZWE,3,2,2017,0.628,0.447205,4.0,36.152,0.927,...,22.0,0.563,0.0,0.0,0.533,2.5,32.0,2.0,0.568,3.927602e+10
1719,Zimbabwe,ZWE,3,2,2018,0.634,0.484174,4.0,34.286,0.927,...,22.0,0.569,0.0,0.0,0.532,2.5,30.0,2.5,0.570,4.323933e+10
1720,Zimbabwe,ZWE,3,2,2019,0.638,NaN,4.0,34.571,0.931,...,24.0,0.571,0.0,0.0,0.527,3.0,31.0,2.5,0.587,4.012525e+10

In [10]:
merged_df[merged_df["country_code"] == "YEM"]

,country_name,country_code,Geografical_Region,Economy_Group,year,Life expectancy index,Civil liberties index,CPIA policy and institutions for environmental sustainability rating (1=low to 6=high),Share of seats in parliament (% held by women),Gender Development Index (GDI),...,CPI_score,Human Development Index (HDI),Revolution,type_of_change,Gender Inequality Index (GII),CPIA business regulatory environment rating (1=low to 6=high),PRIndx_score,"CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)",Education index,"GNI, PPP (current international $)"
1700,"Yemen, Rep.",YEM,2,0,<NA>,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [302]:
merged_df.isna().sum().to_frame().reset_index().sort_values(by = 0)

                                                index     0
0                                        country_name     0
1                                        country_code     0
2                                  Geografical_Region     0
3                                       Economy_Group     0
4                                                year    31
5                               Life expectancy index    31
15                                     type_of_change    31
14                                         Revolution    31
11                        Total population (millions)    31
13                      Human Development Index (HDI)    55
20                                    Education index    55
8      Share of seats in parliament (% held by women)    66
21                 GNI, PPP (current international $)   107
9                      Gender Development Index (GDI)   250
16                      Gender Inequality Index (GII)   325
10              Current health expenditure (% of GDP)   422
6                               Civil liberties index   461
12                                          CPI_score   500
18                                       PRIndx_score   534
7   CPIA policy and institutions for environmental...  1085
17  CPIA business regulatory environment rating (1...  1085
19  CPIA transparency, accountability, and corrupt...  1085